USE COLLEGE;
SELECT MAX(DURATION) FROM COURSE;
SELECT MIN(MARKS) FROM STUDENT;
SELECT SUM(MARKS) FROM STUDENT; 

SELECT AVG(MARKS) FROM STUDENT;
SELECT COUNT(MARKS) FROM STUDENT;

SELECT COUNT(MARKS) AS C FROM STUDENT;
# AS MEANS RENAME THE HEADING

SELECT ROLLNO AS SNO FROM STUDENT;

SELECT CITY,COUNT(NAME) FROM STUDENT GROUP BY CITY;
#GROUP BY MEANS GROUP CHEYTHIT COUNT KANDATHUNNU,GROUP BY CHEYTHAAL WHERE COUSE USE CHEYYAN PATTILA.

SELECT COUNT(NAME) FROM STUDENT;
SELECT GRADE,COUNT(NAME) FROM STUDENT GROUP BY GRADE;
SELECT CITY,COUNT(NAME) FROM STUDENT GROUP BY CITY HAVING MAX(MARKS)>90;
#GROP BY USE #CHEYTHATHIN SHESHAM WHERE USE CHEYYAN PATTATHATH KOND USE CHEYYYUNNA MATTONN AAN 'HAVING'.



