create database apple;
drop database apple;
create database fruits;
drop database fruits;
CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE TABLE1(ID INT,NAME VARCHAR(25),
DPT VARCHAR(25),STATUS BOOLEAN);

CREATE TABLE STUDENTS1(ENTROLL_NO INT,STUDENTS_NAME VARCHAR(50),
DOB DATE,GENDER CHAR(50),AGE INT);
CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;

CREATE TABLE EMPLOYEE1(E_ID INT,E_NAME VARCHAR(50),
E_SALARY INT,E_AGE INT,E_GENDER CHAR(20),E_DPT VARCHAR(20));
USE STUDENTS;
CREATE TABLE TABLE2(ROL_NO INT,NAME VARCHAR(25),
ADDRESS VARCHAR(20),PHONE INT,AGE INT);

CREATE DATABASE IF NOT EXISTS STUDENTS;
CREATE DATABASE IF NOT EXISTS STUDENTS2;
DROP DATABASE IF EXISTS STUDENTS2;
SHOW DATABASES;

USE STUDENTS;
SHOW TABLES;



