USE COLLEGE;

SELECT * FROM STUDENT_DETAILS;

SELECT NAME FROM STUDENT_DETAILS WHERE MARKS>(SELECT AVG(MARKS) FROM STUDENT_DETAILS);

#QUERY
SELECT NAME FROM STUDENT_DETAILS WHERE ID % 2 =0;
SELECT NAME FROM STUDENT_DETAILS WHERE MOD(ID,2)=0;

#SUB QUERY
SELECT NAME FROM STUDENT_DETAILS WHERE ID IN 
(SELECT ID FROM STUDENT_DETAILS WHERE ID %2 = 0);

